version: '3'
services:

  postgres:
    image: postgres
    container_name: postgres
    environment:
      POSTGRES_DB: "marketplace"
      POSTGRES_USER: "root"
      POSTGRES_HOST_AUTH_METHOD: "trust"
    networks:
      vidnftnet:
        ipv4_address: 173.26.0.110 
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d marketplace"]
      interval: 2s
      timeout: 50s
      retries: 25        
    ports:
      - 5432:5432

  marketplace:
    #image: marketplace:alphav2
    image: registry.videocoin.net/nft/marketplace:v1.0.0-beta
    container_name: marketplace
    volumes:
    - ./nft-test-credentials.json:/data/config/nft-test-credentials.json
    depends_on:
      postgres:
        condition: service_healthy
    env_file: 
      - marketplace_env.list   
    networks:
      vidnftnet:
        ipv4_address: 173.26.0.120 
    ports:
      - 8088:8088
    command: 'bash -c "/goose -dir /migrations -table marketplace postgres \"host=postgres port=5432 dbname=marketplace sslmode=disable\" up && /marketplace"'

  nft-app:
    image: registry.videocoin.net/nft/marketplace-ui:beta 
    container_name: nft-app 
    env_file:
      -  nft-app_env.list       
    networks:
      vidnftnet:
        ipv4_address: 173.26.0.130 
    ports:
      - 8080:80

networks:
  vidnftnet:
    driver: bridge
    ipam:
      config:
      - subnet: 173.26.0.0/24

